name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Publish ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
            - { target: aarch64-unknown-linux-gnu   , os: ubuntu-20.04 }
            - { target: arm-unknown-linux-gnueabihf , os: ubuntu-20.04 }
            - { target: x86_64-unknown-linux-gnu    , os: ubuntu-20.04 }

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        profile: minimal
        override: true
        target: ${{ matrix.job.target }}

    - name: Build
      run: cargo build --release --all-features

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/speculare-server
        asset_name: speculare-server-${{ github.ref_name }}-${{ matrix.job.target }}
        tag: ${{ github.ref }}
        overwrite: true