name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
            - { target: aarch64-unknown-linux-gnu   , os: ubuntu-20.04 }
            - { target: arm-unknown-linux-gnueabihf , os: ubuntu-20.04 }
            - { target: x86_64-unknown-linux-gnu    , os: ubuntu-20.04 }

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release --all-features

    - name: Add file to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/speculare-server
        fail_on_unmatched_files: true