CREATE TABLE data (
	os VARCHAR(128) NOT NULL,
	hostname VARCHAR(64) NOT NULL,
	uptime BIGINT NOT NULL,
    uuid VARCHAR(48) PRIMARY KEY NOT NULL,
    active_user VARCHAR(32) NOT NULL,
    mac_address VARCHAR(64) NOT NULL,
	created_at TIMESTAMP NOT NULL
);
CREATE TABLE sensors (
	id SERIAL PRIMARY KEY,
	label VARCHAR(128) NOT NULL,
	temp FLOAT NOT NULL,
	data_uuid VARCHAR(48) NOT NULL,
	created_at TIMESTAMP NOT NULL
);
CREATE TABLE disks (
	id SERIAL PRIMARY KEY,
	disk_name VARCHAR(128) NOT NULL,
	mount_point VARCHAR(128) NOT NULL,
	total_space BIGINT NOT NULL,
	avail_space BIGINT NOT NULL,
	data_uuid VARCHAR(48) NOT NULL,
	created_at TIMESTAMP NOT NULL
);
